internal/golada/builder/builder.go, internal/golada/builder/builder_loader.go, internal/golada/builder/builder_test.go, internal/golada/cmd/cleanup.go, internal/golada/cmd/generate.go, internal/golada/cmd/root.go, internal/golada/cmd/version.go, pkg/annotation/annotation.go, pkg/annotation/annotation_test.go, pkg/annotation/csv_parser.go, pkg/annotation/property_parser.go, pkg/compressor/compressor.go, pkg/compressor/compressor_tar.go, pkg/compressor/compressor_tar_test.go, pkg/files/directory.go, pkg/files/files.go, pkg/files/files_test.go, pkg/files/files_util.go, pkg/files/paths/paths.go, pkg/files/paths/paths_test.go, pkg/generator/generator.go, pkg/generator/generator_test.go, pkg/inspector/ast_inspector.go, pkg/inspector/ast_inspector_test.go, pkg/inspector/file_inspector.go, pkg/inspector/file_inspector_test.go, scripts/analysis.sh, scripts/reformat.sh
Add missing license header to shell scripts.
Make sure all Go source files share the exact same license header.
Run `reformat.sh` script.
=> Fix License header in source files

pkg/files/files_util.go
Writes a virtual directory to the disk to improve assets storing on
disk. Checks if the directory is a root directory in which case it will
write everything in the directory to the path. If not the WriteToDisk
method will first create a sub-directory in the path, in which it stores
the contents of the passed virtual directory.
This fixes #6
=> Introduces method to write directory to disk

README.md
Pina-Golada has been to the homeport Homebrew tap to improve macOS
installations. The README now contains a shell command to install it.
This PR should fixes #7
=> Adds brew install guide to README

README.md, internal/golada/builder/builder.go, internal/golada/builder/builder_test.go, internal/golada/cmd/generate.go, pkg/inspector/ast_inspector.go, pkg/inspector/ast_inspector_test.go
This commit removes the need to specify the package by catching the
ast.File node in the astStream. The File node is then passed in a
wrapper instance to the interfaces. The astStream now processes nodes by
File rather than by order. The README was adapted to these changes.
This fixes #3
=> Removes the need to specify the package

Makefile, pkg/files/files_util.go
This commit adds the parameter permission to the WriteToDisk method
as the permissions the files are created with, should be determined by
the executing program not pina-golada.
Note: I will merge this on my own as it is currently preventing me from working on watchful and the change is not big at all.
=> Hotfix: Enables custom permission for writing files onto the disk

pkg/compressor/compressor_tar.go, pkg/files/directory.go, pkg/files/files.go, pkg/files/files_test.go, pkg/files/files_util.go
As a sub directory may be used as a base for future operations, creating
a rooted copy of it, helps.
This also allows to copy only a directories content if the directory is
not the root directory
=> Introduces Directory#AsRoot to create a root copy

pkg/files/files_util.go
When writing a file to the file system using WriteToDisk, the file
writer instance that is created when creating the file from scratch is
now being closed, allowing the program instantly work on the written
file
=> Fixes open file writer instance on WriteToDisk

pkg/files/directory.go
When creating files/directories that don't have a permission set
assigned, due to compression mechanism etc, pina-golada will now
automatically assign 0755 as the default file permission instead of 0000
=> Adds default permission to files

.travis.yml
Add Go version 1.12 as one of the Go versions to be tested.
=> Add Go version 1.12 to Travis

scripts/test.sh
fix #18 
I fixed the script/test.sh to be disable verbose ginkgo to remove`-v` option
=> remove -v in ginkgo #18

internal/golada/builder/builder_test.go, pkg/generator/generator.go
Break up the function write code to add a condition to only add return
types in parenthesis if there are ones defined.
This should fix issue #29.
=> Omit parenthesis if generated function has no return value

assets/tests/issue-27/directory-1/info.txt, assets/tests/issue-27/directory-2/info.txt, internal/golada/builder/builder_test.go, pkg/generator/generator.go
Replace list of import paths with a simple map structure, where the keys are
the import paths to be used. This way, there is no need to check whether an
import path was already used.
This should fix issue #27.
=> Ensure that import paths are only used once

internal/golada/builder/builder.go
Run the Go formatter code on the generated source code. This increases the
readability if one ever choose to look at the code. Also, it serves as a
simple proof point whether the code is actual compilable Go source code.
=> Run Go Formatter on generated source

internal/golada/builder/builder.go, internal/golada/builder/builder_test.go, internal/golada/builder/builder_test_suite.go, internal/golada/cmd/cleanup.go, internal/golada/cmd/generate.go, internal/golada/cmd/root.go, internal/golada/logger/bunt_logger.go
This commit adds the verbose option by passing a logger instance to the
executing object. The verbose option displays files as well as found
asset files when executed.
This fixed #38.
This pr currently implements the verbose output I personally feel needed. 
If you have more / different needs, please comment below.
=> Adds verbose output option

assets/tests/issue-51/file/permission.txt, pkg/files/files_test.go, pkg/files/files_util.go
If overwrite is set to true when calling WriteToDisk, pina-golada now
overwrites the file permission set if it does not match the one of the
virtual file system.
This push request fixes #51
=> Now overwrites file and directory permissions

README.md, internal/golada/builder/builder.go, internal/golada/cmd/cleanup.go, internal/golada/cmd/generate.go, pkg/annotation/annotation.go, pkg/annotation/annotation_test.go, pkg/annotation/csv_parser.go, pkg/annotation/label_parser.go
This commit adds the build-tag annotation parser, which is supposed to
provide the feel of a go tag instead of the java like annotations
pina-golada was using before. This commit also provides documentation on
how to specify the annotation parser on the command call.
This implements #39
=> Implements a go build-tag like annotation parser

internal/golada/builder/builder.go, pkg/files/files_util.go
The builder used to have its own loader logic as it stores the folder to
load as a sub directory below the root diretory to keep the diretory
name present.
Now the builder does this prior to calling the default LoadFromDisk
method which fixes the lookup issues in the generated asset providers.
This PR fixes #59
=> Fixes builder directory tree

.travis.yml, go.mod, go.sum, internal/golada/builder/builder.go, internal/golada/builder/builder_test_suite.go, internal/golada/cmd/cleanup.go, pkg/annotation/csv_parser.go, pkg/annotation/label_parser.go, pkg/annotation/property_parser.go, pkg/files/directory.go, pkg/files/files_test.go, pkg/files/files_util.go, scripts/test.sh, test/integration/.test/assets/file.txt, test/integration/.test/assets/folder/content.md, test/integration/.test/integration_test.go, test/integration/.test/integration_test_suite.go, test/integration/integration_test.go
As pina-golada did struggle a lot in the latest releases, this commit
adds an integration test to the project which compiles a test project
and tests for correct compilation and write to disk functionality.
As pina-golada generation cannot be dynamically loaded/unloaded, the implemented integration tests basically consist of three states. 
1. The first tests that are run are the pre-tests which generate the asset implementation as well as set up the file permission on the file system. 
2. The second tests are run as an integration which tests for the actual pina-golada code working.
3. The third tests are run as the post-tests which delete local test files and cleans up the pina-golada source.
=> Implements integration test

.travis.yml
Travis should build a release binary when the go version is 1.12. As the
previous PR did remove the 1.11 build configurations, this commit now
fixes build generation.
=> Update travis release condition

.travis.yml, go.mod, go.sum
To make use of the latest ginko version, this commit bumps the minimum
version of pina-golada to golang 1.14.
=> Bump golang version to 1.14
